import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createStore} from '../src/scaleup/store.js';
import {accounts,command,reconcile,eligibility,view,integrity,assess} from '../src/scaleup/domain.js';
import {createScaleUpService} from '../src/scaleup/service.js';
import {createValidationService} from '../src/validation/service.js';
const now='2026-09-10T00:00:00.000Z';
const source={challenges:[],startups:[]};
const input=()=>({packet:{id:'demo:medium',pilotId:'demo:medium',contractId:'demo:medium',pilotDesignId:'pd1',startupId:'demo-startup',departmentId:'demo-department',title:'Synthetic case',startupName:'Synthetic startup',risk:'Medium',synthetic:true},gate:{eligible:true,reasons:[],roundId:'r1',status:'validated'},snapshotHash:'evidence-version-1',snapshot:{kpis:[{key:'accuracy',label:'Accuracy',baseline:60,target:85,mandatory:true}]},findings:[{result:'approved',checks:[{key:'accuracy',verified:true,verifiedValue:90}]}]});
const proposal=()=>({expectedVersion:0,locations:[{name:'Depot A',ready:true,evidence:'Synthetic site inspection completed with full checklist.'}],volume:100,months:12,capacity:150,capacityEvidence:'Synthetic load test covers 150 units concurrently.',upfrontPaise:10000000,monthlyPaise:1000000,baselineUnitMonthlyPaise:30000,costEvidence:'Synthetic baseline and total costs independently itemised.',assumptions:'Maintenance included for the proposed 12-month period.',risks:['security','continuity','dataIP'].map(key=>({key,critical:true,effective:true,evidence:'Synthetic mitigation evidence independently assessed.'})),reason:'Synthetic proposal for a bounded expansion assessment.'});
function setup(){const db=createStore(':memory:'),s=db.read();db.close();return {s,c:input(),registry:accounts(source)};}
const actor=(f,role)=>f.registry.find(a=>a.role===role);
const rec=f=>f.s.recommendations.at(-1);
function run(f,role,action,payload){command(f.s,[f.c],f.registry,actor(f,role),f.c.packet.id,action,payload,now);reconcile(f.s,[f.c],now);}
function submit(f,p=proposal()){run(f,'proposer','submit',p);}
function approve(f,role,extra={}){run(f,role,'review',{recommendationId:rec(f).id,inputHash:rec(f).inputHash,noConflict:true,result:'approve',reason:'Independent checks of evidence, scope and authorisation complete.',fundingReference:'Demo funding approval reference FIN-001.',fundingPaise:22000000,costVerified:true,pathwayReference:'Demo procurement assessment reference PR-001.',requirementsSatisfied:true,scopeConfirmed:true,validUntil:'2026-10-01T00:00:00.000Z',...extra});}
function full(f){submit(f);approve(f,'finance');approve(f,'procurement');approve(f,'authority');}
test('validated scoped evidence produces deterministic score with no automatic approval',()=>{const f=setup();submit(f);assert.equal(rec(f).finalScore,100);assert.equal(rec(f).recommendation,'phased_expansion_review');assert.equal(eligibility(f.s,f.c,now,f.registry).eligible,false);reconcile(f.s,[f.c],now);assert.equal(f.s.recommendations.length,1);assert.equal(integrity(f.s),true);});
test('missing validation, mandatory failures and critical controls block scoring',()=>{const f=setup();f.c.gate={eligible:false,reasons:['Missing independent validation.'],roundId:null};submit(f);assert.equal(rec(f).finalScore,null);const g=setup();g.c.findings[0].checks[0].verifiedValue=70;submit(g);assert.equal(rec(g).finalScore,null);const h=setup(),p=proposal();p.risks[0].effective=false;submit(h,p);assert.equal(rec(h).recommendation,'discontinue_review');assert.equal(rec(h).finalScore,null);});
test('capacity or location gaps prevent expansion even with a high weighted score',()=>{const f=setup(),p=proposal();p.capacity=99;submit(f,p);assert.ok(rec(f).finalScore>=80);assert.equal(rec(f).recommendation,'additional_pilot');approve(f,'finance');approve(f,'procurement');assert.throws(()=>approve(f,'authority'),/phased expansion/);});
test('department costs are recalculated; duplicate locations and unsafe amounts are rejected',()=>{const f=setup(),p=proposal();p.totalPaise=1;submit(f,p);assert.equal(f.s.proposals[0].facts.totalPaise,22000000);const g=setup(),q=proposal();q.locations.push({...q.locations[0]});assert.throws(()=>submit(g,q),/Duplicate locations/);q.locations.pop();q.monthlyPaise=Infinity;assert.throws(()=>submit(g,q),/integer paise/);});
test('startup/admin cannot approve and stages enforce independent people',()=>{const f=setup();submit(f);assert.throws(()=>approve(f,'authority'),/awaiting_finance/);assert.throws(()=>approve(f,'admin'),/authority/);approve(f,'finance');actor(f,'procurement').personId=actor(f,'finance').personId;assert.throws(()=>approve(f,'procurement'),/separate person/);});
test('funding and procurement evidence are mandatory, failures cannot be approved through UI payloads',()=>{const f=setup();submit(f);assert.throws(()=>approve(f,'finance',{fundingPaise:100}),/cover/);assert.throws(()=>approve(f,'finance',{costVerified:false}),/Verify cost/);approve(f,'finance');assert.throws(()=>approve(f,'procurement',{requirementsSatisfied:false}),/Resolve procurement/);});
test('final approval binds scope and expiry; duplicate approval and expired decisions are blocked',()=>{const f=setup();full(f);assert.equal(eligibility(f.s,f.c,now,f.registry).eligible,true);assert.equal(f.s.decisions[0].approvedScope.volume,100);assert.throws(()=>approve(f,'authority'),/stage/);assert.equal(eligibility(f.s,f.c,'2027-01-01T00:00:00.000Z',f.registry).eligible,false);actor(f,'finance').authority=null;assert.equal(eligibility(f.s,f.c,now,f.registry).eligible,false);});
test('material validation changes stale the approval; changed evidence is snapshotted immutably',()=>{const f=setup();full(f);const prior=rec(f);f.c.snapshotHash='new-version';f.c.findings[0].checks[0].verifiedValue=87;assert.equal(eligibility(f.s,f.c,now,f.registry).eligible,false);reconcile(f.s,[f.c],now);assert.equal(f.s.recommendations.length,2);assert.equal(prior.inputSnapshot.findings[0].checks[0].verifiedValue,90);assert.equal(integrity(f.s),true);});
test('new scope needs new approvals and stale form versions are rejected',()=>{const f=setup();full(f);const p=proposal();p.expectedVersion=1;p.volume=110;submit(f,p);assert.equal(eligibility(f.s,f.c,now,f.registry).eligible,false);assert.throws(()=>submit(f,p),/changed/);assert.equal(f.s.decisions.length,1);});
test('ordinary payment changes do not penalise scores; open dispute gate blocks',()=>{const f=setup();full(f);f.c.packet.milestones=[{payment:{status:'paid'}}];reconcile(f.s,[f.c],now);assert.equal(f.s.recommendations.length,1);assert.equal(eligibility(f.s,f.c,now,f.registry).eligible,true);f.c.gate.eligible=false;f.c.gate.reasons=['Resolve open dispute.'];reconcile(f.s,[f.c],now);assert.equal(rec(f).finalScore,null);});
test('decision tampering is detected; SQLite immutable records survive restart',()=>{const f=setup();full(f);const dir=fs.mkdtempSync(path.join(os.tmpdir(),'scaleup-test-')),file=path.join(dir,'test.sqlite');let store=createStore(file);store.transaction(s=>Object.assign(s,f.s));assert.throws(()=>store.transaction(s=>{s.decisions[0].approvedScope.volume=999;}),/overwritten/);store.close();store=createStore(file);assert.equal(integrity(store.read()),true);store.close();fs.rmSync(dir,{recursive:true,force:true});f.s.decisions[0].approvedScope.volume=999;assert.equal(integrity(f.s),false);});
test('overdue notifications deduplicate; closed reviews never auto-approve',()=>{const f=setup();submit(f);reconcile(f.s,[f.c],'2026-10-01T00:00:00.000Z');reconcile(f.s,[f.c],'2026-10-01T00:00:00.000Z');assert.equal(f.s.notifications.filter(n=>n.key.startsWith('overdue:')).length,1);assert.equal(f.s.decisions.length,0);});
test('Feature 9 adapter exposes current gate without leaking validator identities',()=>{const validation=createValidationService({readSource:()=>source,readPayments:()=>({}),filename:':memory:',intervalMs:0,now:()=>now,rng:()=>0});try{const cases=validation.scaleUpInputs();assert.equal(cases.length,2);assert.equal(cases[0].gate.eligible,false);assert.ok(!JSON.stringify(cases[0].findings).includes('validator:'));}finally{validation.close();}});
test('handoff retries safely and rechecks current authorisation before side effects',()=>{const f=setup();f.c.packet.synthetic=false;full(f);run(f,'authority','activate',{recommendationId:rec(f).id,inputHash:rec(f).inputHash,noConflict:true});let calls=0;const service=createScaleUpService({readSource:()=>source,readValidation:()=>[f.c],filename:':memory:',intervalMs:0,now:()=>now,applyHandoff:()=>{calls++;if(calls===1)throw Error('Temporary adapter failure');}});try{service.store.transaction(s=>Object.assign(s,f.s));service.dispatch();assert.equal(service.store.read().handoffs[0].status,'queued');service.dispatch();assert.equal(service.store.read().handoffs[0].status,'completed');service.dispatch();assert.equal(calls,2);}finally{service.close();}const g=setup();full(g);run(g,'authority','activate',{recommendationId:rec(g).id,inputHash:rec(g).inputHash,noConflict:true});g.c.gate.eligible=false;const blocked=createScaleUpService({readSource:()=>source,readValidation:()=>[g.c],filename:':memory:',intervalMs:0,now:()=>now});try{blocked.store.transaction(s=>Object.assign(s,g.s));blocked.dispatch();assert.equal(blocked.store.read().handoffs[0].status,'blocked');}finally{blocked.close();}});
test('HTTP auth, cross-origin protection, idempotency, export and version conflicts',async()=>{const f=setup();const service=createScaleUpService({readSource:()=>source,readValidation:()=>[f.c],filename:':memory:',intervalMs:0,now:()=>now}),app=express();app.use(express.json());app.use('/api/scale-up',service.router);const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));try{const base=`http://127.0.0.1:${server.address().port}/api/scale-up`;assert.equal((await fetch(base)).status,401);assert.equal((await fetch(base+'/accounts',{headers:{Origin:'https://bad.invalid'}})).status,403);const login=await fetch(base+'/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accountId:actor(f,'proposer').id})});const cookie=login.headers.get('set-cookie').split(';')[0],headers={cookie,'Content-Type':'application/json','Idempotency-Key':'proposal-key-001'},request={method:'POST',headers,body:JSON.stringify(proposal())};const responses=await Promise.all([fetch(base+'/demo%3Amedium/submit',request),fetch(base+'/demo%3Amedium/submit',request)]);assert.deepEqual(responses.map(r=>r.status),[200,200]);assert.equal(service.store.read().proposals.length,1);assert.equal((await fetch(base+'/demo%3Amedium/submit',{...request,body:JSON.stringify({...proposal(),volume:101})})).status,409);const report=await(await fetch(base+'/demo%3Amedium/export',{headers:{cookie}})).json();assert.equal(report.label,'DRAFT — NOT AUTHORISED');}finally{await new Promise(resolve=>server.close(resolve));service.close();}});
