import express from 'express';
import apiRouter, { setPaymentProjection, setValidationGate } from './src/routes.js';
import { readDB, writeDB } from './src/db.js';
import { createPaymentService } from './src/payment/service.js';
import { createValidationService } from './src/validation/service.js';
import { createScaleUpService } from './src/scaleup/service.js';
const app=express();
const payments=createPaymentService({readSource:readDB});
setPaymentProjection(payments.projectContract);
const validation=createValidationService({readSource:readDB,readPayments:()=>{payments.sync();return payments.store.read();}});
setValidationGate(validation.gateForDesign);
const scaleup=createScaleUpService({readSource:readDB,readValidation:validation.scaleUpInputs,applyHandoff(h,packet){
  const db=readDB(),pd=(db.pilotDesigns||[]).find(p=>p.id===packet.pilotDesignId);
  if(!pd)throw Error('Linked pilot design missing.');
  if(pd.scaleUpAuthorization?.handoffId===h.id)return;
  const index=pd.phases.findIndex(p=>p.status==='Active');
  if(index<0||pd.phases[index+1]?.key!=='live')throw Error('Field pilot must be active before live handover.');
  pd.phases[index].status='Passed';pd.phases[index].passedAt=new Date().toISOString();pd.phases[index+1].status='Active';
  pd.scaleUpAuthorization={handoffId:h.id,decisionId:h.decisionId,scope:h.scope,mode:'local-demo',at:new Date().toISOString()};
  writeDB(db);
}});
app.use(express.json({limit:'1600kb'}));
app.use('/api/payments',payments.router);
app.use('/api/validation',validation.router);
app.use('/api/scale-up',scaleup.router);
app.use('/api',apiRouter);
app.use((err,_req,res,_next)=>res.status(err.status||500).json({error:err.status===413?'Upload too large. Maximum file size is 1 MB.':'Request could not be processed.'}));
const port=process.env.PORT||4001;
const server=app.listen(port,'127.0.0.1',()=>console.log(`Vyavsay listening at http://127.0.0.1:${port} (local seed-connected payment demo)`));
function shutdown(){server.close(()=>{scaleup.close();payments.close();validation.close();process.exit(0);});}
process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
