import React,{useEffect,useState} from 'react';
import './payments.css';
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format((n||0)/100);
const date=s=>s?new Date(s).toLocaleString('en-IN'):'—';
const labels={setup_required:'Terms need approval',approved_demo:'Demo terms approved',awaiting_submission:'Awaiting submission',department_review:'Department review',correction_requested:'Correction requested',rejected:'Rejected · dispute available',accepted:'Delivery accepted',imported_history:'Imported paid claim · unverified',approval_pending:'Finance approval',approved:'Approved · not paid',processing:'Processing',failed:'Payment failed',status_unknown:'Outcome unknown · reconcile first',paid:'Paid (simulated)'};
async function api(path='',body){
 const r=await fetch('/api/payments'+path,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(body?{'Idempotency-Key':crypto.randomUUID()}:{})},...(body?{method:'POST',body:JSON.stringify(body)}:{})});
 const d=await r.json().catch(()=>({error:'The backend is unavailable. Check the local server.'}));if(!r.ok)throw new Error(d.error||'Request failed');return d;
}
const PLATFORM_PAYMENT_ROLE={'Startup':'startup','Government Official':'department'};
export default function PaymentsWorkspace({platformRole='',organisationName=''}){
 const [accounts,setAccounts]=useState([]),[data,setData]=useState(null),[account,setAccount]=useState(''),[contractId,setContractId]=useState(''),[milestoneId,setMilestoneId]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const lockedRole=PLATFORM_PAYMENT_ROLE[platformRole]||null;
 const [criteria,setCriteria]=useState({}),[independent,setIndependent]=useState({}),[reviewDays,setReviewDays]=useState(3),[paymentDays,setPaymentDays]=useState(10),[invoiceNumber,setInvoiceNumber]=useState(''),[invoiceDate,setInvoiceDate]=useState(''),[report,setReport]=useState(''),[attachment,setAttachment]=useState(null),[reason,setReason]=useState(''),[checked,setChecked]=useState(false),[funding,setFunding]=useState(''),[filter,setFilter]=useState('all');
 const receive=d=>{setData(d);setAccount(d.actor.id);setChecked(false);setReason('');};
 useEffect(()=>{let cancelled=false;setData(null);setAccount('');setError('');(async()=>{try{
  const listed=await api('/accounts');if(cancelled)return;setAccounts(listed.accounts);
  if(lockedRole){
   const candidates=listed.accounts.filter(a=>a.role===lockedRole);
   const wanted=(organisationName||'').trim().toLowerCase();
   const selected=wanted?candidates.find(a=>a.name.toLowerCase().startsWith(wanted+' ·')):candidates[0];
   if(!selected)throw new Error('No payment account is configured for this signed-in role.');
   await api('/session',{accountId:selected.id});if(cancelled)return;receive(await api());
  }else{
   try{receive(await api());}catch(e){if(!e.message.includes('Choose a payment'))throw e;}
  }
 }catch(e){if(!cancelled)setError(e.message);}})();return()=>{cancelled=true;};},[lockedRole,organisationName]);
 const c=data?.contracts.find(c=>c.id===contractId)||data?.contracts[0];
 const rows=data?.milestones.filter(m=>m.contractId===c?.id)||[];
 const m=rows.find(m=>m.id===milestoneId)||rows.find(m=>m.state!=='imported_history'&&m.payment?.status!=='paid')||rows[0],p=m?.payment,role=data?.actor.role;
 useEffect(()=>{setChecked(false);setReason('');setInvoiceNumber(m?.submission?.invoiceNumber||'');setInvoiceDate(m?.submission?.invoiceDate||data?.now?.slice(0,10)||'');setReport(m?.state==='correction_requested'?m.submission?.report||'':'');setAttachment(null);},[m?.id,m?.submission?.id,account]);
 const run=async(fn,message)=>{setBusy(true);setError('');setNotice('');try{await fn();if(message)setNotice(message);}catch(e){setError(e.message);}finally{setBusy(false);}};
 const act=(action,payload={},target=m?.id)=>run(async()=>receive(await api('/'+target+'/'+action,{...payload,...(target===m?.id?{expectedVersion:m.version}:{})})),'Saved.');
 const login=id=>run(async()=>{await api('/session',{accountId:id});receive(await api());});
 const refresh=()=>run(async()=>receive(await api()));
 const changeMilestone=id=>{setMilestoneId(id);setChecked(false);setReason('');setNotice('');setError('');};
 const visibleRows=rows.filter(m=>filter==='all'||filter==='overdue'&&(m.reviewOverdue||m.paymentOverdue)||filter==='pending'&&m.state!=='imported_history'&&m.payment?.status!=='paid');
 async function loadFile(file){if(!file){setAttachment(null);return;}if(file.size>1000000){setError('File must be at most 1 MB.');return;}const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(const b of bytes)binary+=String.fromCharCode(b);setAttachment({name:file.name,type:file.name.toLowerCase().endsWith('.pdf')?'application/pdf':'text/plain',base64:btoa(binary)});}
 const openDispute=m?.disputes.find(d=>d.status==='open');
 const lastAttempt=m?.attempts[m.attempts.length-1];
 return <section className="pay-workspace">
  <div className="pay-heading"><div><small>FEATURE 8 · CONTRACT-LINKED PAYMENTS</small><h1>{platformRole==='Startup'?'My milestone payments.':platformRole==='Government Official'?'Milestone review & payments.':'Delivery, review, payment.'}</h1><p>{platformRole==='Startup'?'Submit milestone evidence and track every payment from review to settlement.':platformRole==='Government Official'?'Verify startup delivery, create accountable payment obligations, and surface delays.':'One shared record from invoice to settlement.'}</p></div><span className="pay-demo">LOCAL DEMO · NO REAL MONEY</span></div>
  <div className="pay-notice">Contracts and startup identities come from your updated seed. All new approvals, funding and transfers here are demonstrations. Imported “Paid” claims are not verified settlements.</div>
  <div className="pay-accounts">{lockedRole?<div className="pay-identity"><small>SIGNED-IN PAYMENT VIEW</small><strong>{data?.actor?.name||organisationName||platformRole}</strong><span>{platformRole==='Startup'?'Startup workspace':'Department workspace'}</span></div>:<label>Active payment account<select aria-label="Active payment account" value={account} disabled={busy} onChange={e=>login(e.target.value)}><option value="" disabled>Choose an account</option>{['startup','department','finance','reviewer'].map(role=><optgroup key={role} label={role.toUpperCase()}>{accounts.filter(a=>a.role===role).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</optgroup>)}</select></label>}<button disabled={busy||!data} onClick={refresh}>Refresh records</button></div>
  {error&&<div className="pay-error" role="alert">{error}</div>}{notice&&<div className="pay-success" role="status">{notice}</div>}
  {data&&<>
   <div className="pay-metrics"><article><small>{platformRole==='Startup'?'TOTAL RECEIVED · SIMULATED':'PAID THIS QUARTER · SIMULATED'}</small><strong>{money(data.summary.paidThisQuarterPaise)}</strong><span>{data.summary.settledCount} settled payment(s)</span></article><article><small>{platformRole==='Startup'?'PENDING PAYMENT':'OUTSTANDING'}</small><strong>{money(data.summary.pendingPaise)}</strong><span>{platformRole==='Startup'?'Accepted work awaiting settlement':'Accepted obligations not yet settled'}</span></article><article><small>{platformRole==='Startup'?'OVERDUE PAYMENT':'OVERDUE / DELAYED'}</small><strong>{money(data.summary.overduePaise)}</strong><span>{platformRole==='Startup'?'Payments past their configured deadline':data.summary.delayedReviews+' delayed delivery review(s)'}</span></article></div>
   <p className="pay-caption">Average time to pay: {data.summary.averageDaysToPay===null?'No settlements yet':data.summary.averageDaysToPay.toFixed(1)+' calendar days'} · Unverified imported claims: {money(data.summary.importedHistoryPaise)}</p>
   {!c?<article className="pay-card"><h2>No contracts assigned to this account</h2><p>This account cannot see another organisation’s payment records. Create a contract through the contracting feature or choose an account linked to an existing contract.</p></article>:<>
    <div className="pay-toolbar"><label>Contract<select value={c.id} onChange={e=>{setContractId(e.target.value);setMilestoneId('');}}>{data.contracts.map(c=><option key={c.id} value={c.id}>{c.startupName} · {c.id}</option>)}</select></label><span className="pay-status">{labels[c.state]}</span></div>
    <article className="pay-card pay-contract"><h2>{c.challengeTitle}</h2><p>{c.startupName} · {c.departmentName} · {money(c.amountPaise)}</p><p className="pay-caption">Pilot: {c.pilotId||'Not linked'} · {c.scope} · Startup source label: {c.startupSource}</p>
    {c.sourceChanged&&<div className="pay-error">Source contract changed. Payment actions are blocked until the amendment is reconciled.</div>}
    {c.state==='setup_required'?(role==='department'?<form onSubmit={e=>{e.preventDefault();act('configure',{criteria,independent,reviewDays:Number(reviewDays),paymentDays:Number(paymentDays)},c.id);}}><h3>Approve demo acceptance conditions</h3><p>The seed supplies amounts but no approved acceptance criteria or payment policy. Enter these explicitly before allowing invoices.</p>{rows.filter(m=>m.state!=='imported_history').map(m=><div key={m.id}><label>{m.name} · {money(m.amountPaise)}<textarea required minLength={20} rows={2} value={criteria[m.id]||''} onChange={e=>setCriteria({...criteria,[m.id]:e.target.value})} placeholder="Specify measurable tests, required evidence and what counts as accepted work."/></label><label className="pay-check"><input type="checkbox" checked={!!independent[m.id]} onChange={e=>setIndependent({...independent,[m.id]:e.target.checked})}/>Require an independent evidence check before acceptance</label></div>)}<div className="pay-form-row"><label>Review deadline (calendar days)<input type="number" min="1" max="30" required value={reviewDays} onChange={e=>setReviewDays(e.target.value)}/></label><label>Payment deadline (calendar days)<input type="number" min="1" max="90" required value={paymentDays} onChange={e=>setPaymentDays(e.target.value)}/></label></div><p className="pay-caption">Demo policy: payment clock begins after accepted delivery and valid invoice receipt, using the later event. Criteria and policy lock after approval.</p><button disabled={busy}>Approve and lock demo terms</button></form>:<p>Choose the assigned department reviewer to set and approve the missing demo acceptance criteria.</p>):<p>Review within {c.policy.reviewDays} calendar days. Payment within {c.policy.paymentDays} calendar days after accepted delivery and valid invoice receipt. Demo policy v{c.policy.version}.</p>}
    {role==='finance'&&c.state==='approved_demo'&&<details><summary>Simulated funding allocation · {money(c.fundingPaise)}</summary><label>Available allocation (rupees)<input type="number" min="0" step="0.01" value={funding} onChange={e=>setFunding(e.target.value)}/></label><button disabled={busy||funding===''} onClick={()=>act('funding',{fundingPaise:Math.round(Number(funding)*100)},c.id)}>Update simulated allocation</button><p className="pay-caption">Existing commitments cannot be removed. This is not a treasury balance.</p></details>}
    </article>
    <div className="pay-toolbar"><h2>{platformRole==='Startup'?'My milestones':platformRole==='Government Official'?'Milestone review queue':'Milestones'}</h2><label className="pay-filter">Show<select aria-label="Milestone filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All milestones</option><option value="pending">Unsettled milestones</option><option value="overdue">Overdue reviews/payments</option></select></label></div>
    <div className="pay-table-wrap"><table className="pay-table"><thead><tr><th>Milestone</th><th>Amount</th><th>Status</th><th>Payment due</th></tr></thead><tbody>{visibleRows.map(item=><tr key={item.id} className={item.id===m?.id?'selected':''}><td><button className="pay-link" onClick={()=>changeMilestone(item.id)}>{item.name}</button><small>{item.id}</small></td><td>{money(item.amountPaise)}</td><td>{labels[item.payment?.status||item.state]}{(item.reviewOverdue||item.paymentOverdue)&&<b className="pay-overdue">Overdue</b>}{item.payment?.fundingHold&&<b className="pay-overdue">Funding hold</b>}</td><td>{item.payment?new Date(item.payment.dueAt).toLocaleDateString('en-IN'):'Not started'}</td></tr>)}</tbody></table>{!visibleRows.length&&<p>No milestones match this filter.</p>}</div>
    {m&&<div className="pay-columns" key={m.id}><article className="pay-card"><h2>{m.name}</h2><p>{m.criteria||'Acceptance conditions not supplied for this imported record.'}</p><p className="pay-caption">Delivery target: {date(m.deliveryDueAt)} · Review deadline: {date(m.reviewDueAt)} · Days since first submission: {m.daysPending}</p>
     {m.state==='imported_history'?<div className="pay-notice">The seed says this milestone was paid. No invoice or settlement evidence was supplied, so it is excluded from confirmed-payment totals and reserved against the contract ceiling to prevent duplicate payment.</div>:null}
     {m.decision&&<div className="pay-review"><b>Last department decision: {m.decision.decision}</b><p>{m.decision.reason}</p><small>{date(m.decision.at)}</small></div>}
     {role==='startup'&&['awaiting_submission','correction_requested'].includes(m.state)&&c.state==='approved_demo'&&<form onSubmit={e=>{e.preventDefault();act('submit',{invoiceNumber,invoiceDate,amountPaise:m.amountPaise,report,attachment,confirmed:checked});}}><h3>{m.state==='correction_requested'?'Submit a corrected version':'Submit invoice and evidence'}</h3><label>Invoice number<input required maxLength={80} value={invoiceNumber} onChange={e=>setInvoiceNumber(e.target.value)}/></label><label>Invoice date<input required type="date" value={invoiceDate} max={data.now.slice(0,10)} onChange={e=>setInvoiceDate(e.target.value)}/></label><p>Invoice amount: <b>{money(m.amountPaise)}</b> · Full milestone only; no deductions in this demo.</p><label>Evidence description<textarea required minLength={20} maxLength={50000} rows={5} value={report} onChange={e=>setReport(e.target.value)} placeholder="State what was tested, measured results, source, and limitations. Label simulated results."/></label><label>Supporting file (optional PDF/TXT, max 1 MB)<input type="file" accept=".pdf,.txt" disabled={busy} onChange={e=>loadFile(e.target.files[0]).catch(()=>setError('Could not read this file.'))}/></label><label className="pay-check"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>I confirm this is a demonstration submission for this milestone.</label><button disabled={busy||!checked}>Submit for review</button></form>}
     {m.submission&&<><h3>Evidence version {m.submission.version}</h3><p>Invoice {m.submission.invoiceNumber} · {date(m.submission.submittedAt)}</p>{m.submission.duplicateEvidence&&<div className="pay-notice">Evidence also appears on another milestone. This is a review flag, not a fraud finding.</div>}<pre className="pay-report">{m.submission.report}</pre><a href={'/api/payments/submissions/'+m.submission.id+'/evidence'}>Download {m.submission.attachment?.name||'report'}</a><details><summary>Evidence fingerprint</summary><code>{m.submission.evidenceHash}</code><p className="pay-caption">Binds review to this version. It does not prove that the evidence is true.</p></details></>}
    </article><article className="pay-card"><h2>{platformRole==='Startup'?'Payment status & actions':platformRole==='Government Official'?'Department review & actions':'Review & actions'}</h2><span className="pay-status">{labels[p?.status||m.state]}</span>
     {m.independentRequired&&<p>Independent check: {m.independentReview?m.independentReview.decision:'required before acceptance'}</p>}
     {role==='department'&&m.state==='department_review'&&<><label>Findings against acceptance criteria<textarea rows={3} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain acceptance, specific corrections, or rejection."/></label><label className="pay-check"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>I checked this invoice and evidence version against the acceptance criteria.</label><div className="pay-actions"><button disabled={busy||!checked} onClick={()=>act('review',{decision:'accept',reason,evidenceHash:m.submission.evidenceHash,invoiceValid:checked,criteriaMet:checked,reuseReason:m.submission.duplicateEvidence?reason:null})}>Accept & create payment request</button><button className="pay-secondary" disabled={busy} onClick={()=>act('review',{decision:'correct',reason,evidenceHash:m.submission.evidenceHash})}>Request corrections</button><button className="pay-danger" disabled={busy} onClick={()=>act('review',{decision:'reject',reason,evidenceHash:m.submission.evidenceHash})}>Reject with reason</button></div></>}
     {role==='reviewer'&&m.state==='department_review'&&m.independentRequired&&<><label>Independent findings<textarea value={reason} onChange={e=>setReason(e.target.value)} rows={3}/></label><label className="pay-check"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>I have no conflict of interest and reviewed this version.</label><div className="pay-actions">{['pass','fail'].map(decision=><button key={decision} disabled={busy||!checked} onClick={()=>act('independent-review',{decision,reason,noConflict:checked,evidenceHash:m.submission.evidenceHash})}>{decision==='pass'?'Confirm evidence check':'Flag failed check'}</button>)}</div></>}
     {role==='finance'&&p?.status==='approval_pending'&&<><p>Accepted {date(m.acceptedAt)}. Due {date(p.dueAt)}.</p>{p.fundingHold&&<div className="pay-error">Insufficient simulated funding. Adjust the allocation before retrying approval.</div>}<label className="pay-check"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>I reviewed {money(p.amountPaise)}, the accepted invoice and demo payee.</label><button disabled={busy||!checked||!!openDispute} onClick={()=>act('approve',{confirmed:checked})}>Approve payment</button></>}
     {role==='finance'&&['approved','failed'].includes(p?.status)&&<><p>No settlement has occurred. The obligation and original deadline remain unchanged.</p><button disabled={busy||!!openDispute} onClick={()=>act('initiate')}>{p.status==='failed'?'Retry simulated transfer':'Start simulated transfer'}</button></>}
     {role==='finance'&&['processing','status_unknown'].includes(p?.status)&&<><p>{p.status==='status_unknown'?'Outcome unknown. A new attempt is blocked. Reconcile this original attempt.':'Choose an external-system outcome in the simulator.'}</p><div className="pay-actions"><button disabled={busy} onClick={()=>act('simulate',{attemptId:lastAttempt.id,outcome:'success'})}>Simulate {p.status==='status_unknown'?'reconciled success':'success'}</button><button className="pay-danger" disabled={busy} onClick={()=>act('simulate',{attemptId:lastAttempt.id,outcome:'failure'})}>Simulate confirmed failure</button>{p.status==='processing'&&<button className="pay-secondary" disabled={busy} onClick={()=>act('simulate',{attemptId:lastAttempt.id,outcome:'timeout'})}>Simulate timeout</button>}</div></>}
     {p?.status==='paid'&&<div className="pay-success"><p>Settled in the simulator on {date(p.paidAt)}.</p><code>{p.transactionReference}</code></div>}
     {openDispute&&<div className="pay-notice"><b>Open dispute · payment initiation on hold</b><p>{openDispute.reason}</p><p>Assigned: {openDispute.assignedName}<br/>Response due: {date(openDispute.responseDueAt)}</p></div>}
     {role==='reviewer'&&openDispute?.assignedTo===account&&<><label>Dispute resolution<textarea value={reason} onChange={e=>setReason(e.target.value)} rows={3}/></label><label className="pay-check"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>I have no conflict of interest.</label><button disabled={busy||!checked} onClick={()=>act('resolve-dispute',{disputeId:openDispute.id,decision:'uphold',reason,noConflict:checked})}>Resolve with recorded findings</button>{!p&&<button className="pay-secondary" disabled={busy||!checked} onClick={()=>act('resolve-dispute',{disputeId:openDispute.id,decision:'reopen',reason,noConflict:checked})}>Reopen for correction</button>}</>}
     {m.firstSubmittedAt&&role!=='reviewer'&&<details><summary>Raise a dispute or escalation</summary><label>Reason<textarea value={reason} onChange={e=>setReason(e.target.value)} rows={3}/></label><button disabled={busy||!!openDispute} onClick={()=>act('dispute',{reason})}>Request independent dispute review</button><button disabled={busy} className="pay-secondary" onClick={()=>act('escalate',{reason})}>Escalate delay</button></details>}
     <h3>Activity history</h3><ol className="pay-history">{m.history.map(e=><li key={e.id}><b>{e.action}</b><span>{e.actorName} · {date(e.at)}</span>{e.details.reason&&<p>{e.details.reason}</p>}</li>)}</ol>
     {m.attempts.length>0&&<details><summary>Payment attempts ({m.attempts.length})</summary>{m.attempts.map(a=><p key={a.id}><code>{a.id}</code><br/>{a.status} · {date(a.createdAt)}</p>)}</details>}
    </article></div>}
   </>}
   <article className="pay-card pay-alerts"><h2>{platformRole==='Startup'?'Payment alerts':platformRole==='Government Official'?'Review & payment alerts':'Alerts & scheduled checks'}</h2><p className="pay-caption">Background checks run every minute while the local backend is running. Last successful check: {date(data.lastDeadlineCheck)}. Notifications are in-app; email delivery is not connected.</p>{data.workerError&&<div role="alert" className="pay-error">{data.workerError}</div>}{data.notifications.length?data.notifications.map(n=><div key={n.id} className="pay-alert"><b>{n.type.replaceAll('_',' ')}</b><p>{n.message}</p><small>{date(n.createdAt)} · {n.milestoneId}</small></div>):<p>No alerts yet.</p>}
    {role==='reviewer'&&<details><summary>Demo clock controls</summary><p>Current demo time: {date(data.now)}. Offset: {data.clockOffsetDays} day(s). Advance time to test deadlines without editing submission dates. This affects all local payment records and cannot be reversed through this screen.</p><button disabled={busy} onClick={()=>act('advance-clock',{days:4},'demo')}>Advance demo by 4 days</button></details>}
   </article>
  </>}
 </section>;
}
