import React,{useEffect,useState} from 'react';
import './validation.css';
const money=n=>n==null?'—':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n/100);
const label=s=>(s||'').replaceAll('_',' ');
async function api(path='',options={}){const r=await fetch('/api/scale-up'+path,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...options.headers}});const b=await r.json();if(!r.ok)throw Object.assign(new Error(b.error||'Request failed'),{status:r.status});return b;}
const empty=()=>({locations:[{name:'',ready:false,evidence:''}],volume:'',months:'',capacity:'',capacityEvidence:'',upfrontPaise:'',monthlyPaise:'',baselineUnitMonthlyPaise:'',costEvidence:'',assumptions:'',risks:['security','continuity','dataIP'].map(key=>({key,effective:false,critical:true,evidence:''}))});
const synthetic=()=>({locations:[{name:'Synthetic depot A',ready:true,evidence:'Synthetic site readiness checklist; all infrastructure checks passed.'},{name:'Synthetic depot B',ready:true,evidence:'Synthetic integration and staffing checklist; no real inspection.'}],volume:100,months:12,capacity:150,capacityEvidence:'Synthetic capacity test supports 150 units; not a supplier guarantee.',upfrontPaise:10000000,monthlyPaise:1000000,baselineUnitMonthlyPaise:30000,costEvidence:'Synthetic baseline of INR 300 per unit/month; estimate includes setup and operations.',assumptions:'Synthetic 12-month fixed-volume estimate, maintenance included; no real quotation.',risks:['security','continuity','dataIP'].map(key=>({key,effective:true,critical:true,evidence:'Synthetic control assessment completed for '+key+'; no real certification.'}))});
export default function ScaleUpWorkspace({onValidation}){
 const [accounts,setAccounts]=useState([]),[data,setData]=useState(null),[id,setId]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[retry,setRetry]=useState(null);
 const [form,setForm]=useState(empty),[reason,setReason]=useState(''),[noConflict,setNoConflict]=useState(false),[fundingReference,setFundingReference]=useState(''),[funding,setFunding]=useState(''),[costVerified,setCostVerified]=useState(false),[pathway,setPathway]=useState(''),[requirements,setRequirements]=useState(false),[scope,setScope]=useState(false),[expiry,setExpiry]=useState('');
 const actor=data?.actor,item=data?.cases.find(c=>c.case.id===id)||data?.cases[0],rec=item?.recommendation;
 const set=(k,v)=>setForm(s=>({...s,[k]:v}));
 useEffect(()=>{let active=true;api('/accounts').then(r=>active&&setAccounts(r.accounts)).catch(e=>active&&setError(e.message));api().then(r=>active&&setData(r)).catch(e=>e.status!==401&&active&&setError(e.message));return()=>{active=false;};},[]);
 useEffect(()=>{if(!actor)return;const timer=setInterval(()=>api().then(setData).catch(e=>setError(e.message)),30000);return()=>clearInterval(timer);},[actor?.id]);
 useEffect(()=>{setForm(item?.proposal?.facts||empty());setReason('');setNoConflict(false);setRetry(null);setFunding('');setFundingReference('');setPathway('');setRequirements(false);setCostVerified(false);setScope(false);setExpiry('');},[item?.case.id,actor?.id,item?.proposal?.id,rec?.id]);
 async function login(accountId){setBusy(true);setError('');try{await api('/session',{method:'POST',body:JSON.stringify({accountId})});setData(await api());}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function refresh(){try{setData(await api());setError('');}catch(e){setError(e.message);}}
 async function send(action,body,saved=null){const req=saved||{path:`/${encodeURIComponent(item.case.id)}/${action}`,body,key:crypto.randomUUID()};setBusy(true);setError('');try{setData(await api(req.path,{method:'POST',headers:{'Idempotency-Key':req.key},body:JSON.stringify(req.body)}));setRetry(null);setReason('');}catch(e){setError(e.message);setRetry(e.status?null:req);}finally{setBusy(false);}}
 function submit(){send('submit',{...form,volume:Number(form.volume),months:Number(form.months),capacity:Number(form.capacity),upfrontPaise:Number(form.upfrontPaise),monthlyPaise:Number(form.monthlyPaise),baselineUnitMonthlyPaise:Number(form.baselineUnitMonthlyPaise),reason,expectedVersion:item.proposal?.version||0});}
 function review(result){send('review',{recommendationId:rec.id,inputHash:rec.inputHash,noConflict,result,reason,fundingReference,fundingPaise:funding===''?null:Math.round(Number(funding)*100),costVerified,pathwayReference:pathway,requirementsSatisfied:requirements,scopeConfirmed:scope,validUntil:expiry?new Date(expiry+'T23:59:59').toISOString():null});}
 const reviewRole={awaiting_finance:'finance',awaiting_procurement:'procurement',awaiting_authority:'authority'}[rec?.status];
 return <section className="validation-workspace"><header><div className="v-eyebrow">FEATURE 10 · EVIDENCE-BASED SCALE-UP</div><h1>Scale-up decisions</h1><p>From verified pilot results to a scoped, reviewed expansion proposal.</p></header>
 <div className="v-banner"><strong>Local demonstration</strong> · Role accounts and delegated authorities are simulated. Recommendations and handovers do not award a contract or move money.</div>
 <div className="v-toolbar v-card"><label>Scale-up account<select aria-label="Scale-up account" disabled={busy} value={actor?.id||''} onChange={e=>login(e.target.value)}><option value="" disabled>Choose an account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Pilot / contract<select aria-label="Scale-up case" disabled={busy||!actor} value={item?.case.id||''} onChange={e=>setId(e.target.value)}><option value="" disabled>Choose a case</option>{data?.cases.map(c=><option key={c.case.id} value={c.case.id}>{c.case.synthetic?'PRACTICE · ':'SEED · '}{c.case.title}</option>)}</select></label><button disabled={busy} onClick={refresh}>Refresh</button></div>
 {error&&<div className="v-error" role="alert">{error}{retry&&<button disabled={busy} onClick={()=>send(null,null,retry)}>Retry the same request</button>}</div>}{data?.workerError&&<div className="v-error">{data.workerError}</div>}{data&&!data.integrity&&<div className="v-error">Audit integrity failed. Approvals are blocked.</div>}
 {!actor&&<div className="v-card">Start with <strong>Demo department · proposer</strong> for a practice proposal. Finish its independent validation in Feature 9 before expecting an expansion recommendation.</div>}{actor&&!item&&<div className="v-card">No cases are available for this account.</div>}
 {item&&<>
 <div className="v-grid"><article className="v-card"><h2>{item.case.startupName}</h2><span className={'v-tag '+(rec?.status==='approved'?'v-good':'')}>{label(rec?.status||'proposal_needed')}</span><p>{item.case.synthetic?'Synthetic practice data':'Linked source record'} · {item.case.risk} risk</p><p>Independent validation: <strong>{label(item.validation.status)}</strong></p>{!item.validation.eligible&&<><ul>{item.validation.reasons.map((r,i)=><li key={i}>{r}</li>)}</ul><button onClick={onValidation}>Open Independent Validation</button></>}<p>Preparation, scoring, routing and overdue alerts run automatically. Officials review evidence and authorise the assessed scope.</p></article>
 <article className="v-card"><h2>Recommendation</h2><p style={{fontSize:30,fontWeight:800}}>{rec?.finalScore==null?'Not scored':`${rec.finalScore}/100`}</p><strong>{label(rec?.recommendation||'Submit a proposal')}</strong><p>{rec?.summary||'No expansion proposal submitted yet.'}</p>{rec?.components&&<>{Object.entries(rec.components).map(([k,v])=><p key={k}>{label(k)}: {v.toFixed(1)} · weight {Math.round(rec.policy.weights[k]*100)}%</p>)}</>}<p className="v-muted">Deterministic explanation · AI disabled · prototype policy v1. No national expansion is inferred from a score.</p></article></div>
 {actor.role==='proposer'&&<div className="v-card"><h2>{item.proposal?'Revise expansion proposal':'Create expansion proposal'}</h2>{item.case.synthetic&&<button disabled={busy} onClick={()=>{setForm(synthetic());setReason('Synthetic scoped expansion proposal for workflow testing only.');}}>Fill synthetic expansion example</button>}
 <p>Enter the evidence for the exact expansion being assessed. New versions invalidate earlier approval applicability.</p>
 {form.locations.map((l,i)=><div className="v-evidence" key={i}><label>Deployment location<input value={l.name} onChange={e=>set('locations',form.locations.map((x,n)=>n===i?{...x,name:e.target.value}:x))}/></label><label>Location readiness evidence<textarea value={l.evidence} onChange={e=>set('locations',form.locations.map((x,n)=>n===i?{...x,evidence:e.target.value}:x))}/></label><label className="v-checkbox"><input type="checkbox" checked={l.ready} onChange={e=>set('locations',form.locations.map((x,n)=>n===i?{...x,ready:e.target.checked}:x))}/>Readiness supported by the cited evidence</label>{form.locations.length>1&&<button onClick={()=>set('locations',form.locations.filter((_,n)=>n!==i))}>Remove location</button>}</div>)}<button onClick={()=>set('locations',[...form.locations,{name:'',ready:false,evidence:''}])}>Add location</button>
 <div className="v-grid">{[['volume','Proposed units'],['months','Duration (months)'],['capacity','Supported unit capacity']].map(([k,t])=><label key={k}>{t}<input type="number" min="1" value={form[k]} onChange={e=>set(k,e.target.value)}/></label>)}</div>
 <label>Capacity evidence<textarea value={form.capacityEvidence} onChange={e=>set('capacityEvidence',e.target.value)}/></label>
 <div className="v-grid">{[['upfrontPaise','Upfront cost (INR)'],['monthlyPaise','Monthly operating cost (INR)'],['baselineUnitMonthlyPaise','Baseline cost per unit/month (INR)']].map(([k,t])=><label key={k}>{t}<input type="number" min="0.01" step="0.01" value={form[k]===''?'':Number(form[k])/100} onChange={e=>set(k,e.target.value===''?'':Math.round(Number(e.target.value)*100))}/></label>)}</div>
 <label>Cost / baseline evidence<textarea value={form.costEvidence} onChange={e=>set('costEvidence',e.target.value)}/></label><label>Cost assumptions and inclusions<textarea value={form.assumptions} onChange={e=>set('assumptions',e.target.value)}/></label>
 {form.risks.map((r,i)=><div className="v-evidence" key={r.key}><h3>{({security:'Security controls',continuity:'Continuity and maintenance',dataIP:'Data and IP controls'})[r.key]}</h3><label>Assessment evidence<textarea value={r.evidence} onChange={e=>set('risks',form.risks.map((x,n)=>n===i?{...x,evidence:e.target.value}:x))}/></label><label className="v-checkbox"><input type="checkbox" checked={r.critical} onChange={e=>set('risks',form.risks.map((x,n)=>n===i?{...x,critical:e.target.checked}:x))}/>Unmitigated failure would be critical</label><label className="v-checkbox"><input type="checkbox" checked={r.effective} onChange={e=>set('risks',form.risks.map((x,n)=>n===i?{...x,effective:e.target.checked}:x))}/>Mitigation is effective, with evidence</label></div>)}
 <label>Submission / revision reason<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="v-actions"><button className="v-primary" disabled={busy} onClick={submit}>Submit for automatic assessment</button>{rec?.status==='expired'&&<button disabled={busy} onClick={()=>send('reassess',{expectedVersion:item.proposal.version,reason})}>Request renewed assessment</button>}</div></div>}
 {item.validationEvidence&&<details className="v-card"><summary>Validated evidence and current payment context</summary><pre>{JSON.stringify({validation:item.validationEvidence,payments:item.paymentContext},null,2)}</pre><p>Raising a dispute is not a scoring penalty. Open unclassified disputes remain blocking until assessed in the upstream workflow.</p></details>}
 {item.proposal&&<div className="v-card"><h2>Assessed scope · version {item.proposal.version}</h2><p>Locations: {item.proposal.facts.locations.map(l=>l.name).join(', ')}</p><p>{item.proposal.facts.volume} units · {item.proposal.facts.months} months · cost ceiling <strong>{money(item.proposal.facts.totalPaise)}</strong></p><details><summary>Expansion evidence and assumptions</summary><pre>{JSON.stringify(item.proposal.facts,null,2)}</pre></details>{rec&&<p className="v-muted">Input snapshot {rec.inputHash.slice(0,20)}… · validation round {rec.inputSnapshot.validationRoundId||'missing'}</p>}</div>}
 {rec&&reviewRole===actor.role&&<div className="v-card"><h2>Your {actor.role} review</h2><label>Findings and decision rationale<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="At least 15 characters; reference the evidence checked."/></label><label className="v-checkbox"><input type="checkbox" checked={noConflict} onChange={e=>setNoConflict(e.target.checked)}/>I have no undisclosed conflict and am authorised for this review.</label>
 {actor.role==='finance'&&<><label>Funding approval reference<textarea value={fundingReference} onChange={e=>setFundingReference(e.target.value)}/></label><label>Approved funding (INR)<input type="number" step="0.01" value={funding} onChange={e=>setFunding(e.target.value)}/></label><label className="v-checkbox"><input type="checkbox" checked={costVerified} onChange={e=>setCostVerified(e.target.checked)}/>Cost assumptions and supporting evidence checked</label></>}
 {actor.role==='procurement'&&<><label>Procurement pathway / review reference<textarea value={pathway} onChange={e=>setPathway(e.target.value)}/></label><label className="v-checkbox"><input type="checkbox" checked={requirements} onChange={e=>setRequirements(e.target.checked)}/>Required procurement and deployment prerequisites are satisfied.</label></>}
 {actor.role==='authority'&&<><label>Approval valid until (within 90 days)<input type="date" value={expiry} onChange={e=>setExpiry(e.target.value)}/></label><label className="v-checkbox"><input type="checkbox" checked={scope} onChange={e=>setScope(e.target.checked)}/>I confirm these exact locations, volume and budget ceiling.</label></>}
 <div className="v-actions">{['approve','request_changes','reject'].map(result=><button disabled={busy||!noConflict} className={result==='approve'?'v-primary':''} key={result} onClick={()=>review(result)}>{label(result)}</button>)}</div></div>}
 {rec&&<div className="v-card"><h2>Review trail and handover</h2>{item.reviews.map(a=><p key={a.id}><strong>{a.stage}: {label(a.result)}</strong> · {a.findings}{a.fundingPaise?` · ${money(a.fundingPaise)}`:''}</p>)}{item.decision&&<p><strong>Department decision: {label(item.decision.result)}</strong> · {item.decision.findings}{item.decision.validUntil?' · Valid until '+new Date(item.decision.validUntil).toLocaleDateString('en-IN'):''}</p>}
 <p>{item.eligibility.eligible?'Current approval permits the assessed handover.':item.eligibility.reasons.join(' ')}</p>
 {actor.role==='authority'&&item.eligibility.eligible&&!item.handoffs.some(h=>h.decisionId===item.decision?.id)&&<><label className="v-checkbox"><input type="checkbox" checked={noConflict} onChange={e=>setNoConflict(e.target.checked)}/>My authority and conflict declaration remain valid.</label><button disabled={busy||!noConflict} onClick={()=>send('activate',{recommendationId:rec.id,inputHash:rec.inputHash,noConflict})}>{item.case.synthetic?'Record synthetic handover':'Request authorised local rollout handover'}</button></>}
 {item.handoffs.map(h=><p key={h.id}>Handover: <strong>{h.status}</strong> {h.synthetic?'(synthetic; no real deployment)':''} {h.lastError||''}</p>)}<p className="v-muted">No funds are transferred. Existing payment obligations are unchanged.</p><div className="v-actions"><a href={`/api/scale-up/${encodeURIComponent(item.case.id)}/export`} download>Download decision report (JSON)</a><button onClick={()=>window.print()}>Print / save as PDF</button></div></div>}
 {item.notifications.length>0&&<div className="v-card"><h2>Follow-up</h2>{item.notifications.map(n=><p key={n.id}>{n.message}</p>)}</div>}
 {item.history.length>0&&<div className="v-card"><h2>Recommendation history</h2>{item.history.map(h=><p key={h.id}>{new Date(h.createdAt).toLocaleString('en-IN')} · {label(h.status)} · {h.score??'Not scored'} · {label(h.recommendation)}</p>)}</div>}
 {actor.role==='admin'&&<details className="v-card"><summary>Audit events ({item.audit.length})</summary>{item.audit.map(e=><div key={e.seq}><p>#{e.seq} {e.type} · {e.actorId}</p><pre>{JSON.stringify(e.data,null,2)}</pre></div>)}</details>}
 </>}
 </section>;
}
